SELECT 
  PAYMENTS.ORDERID AS ORDER_ID,
  ORDERS.CUSTOMER_ID,
  SUM(PAYMENTS.AMOUNT / 100.0) AS AMOUNT
FROM {{ref('stg_payments')}}       AS PAYMENTS
INNER JOIN {{ ref('stg_orders') }} AS ORDERS
ON PAYMENTS.ORDERID   = ORDERS.ORDER_ID
WHERE PAYMENTS.STATUS = 'success'
GROUP BY 1, 2